### ISSUE TITLE
Comment out WireBegin for ESP32

### ISSUE THREAD

**Issue by anthonyjclarke** [G6EJD/ESP_Simple_Clock_Functions#1]
Thanks for sharing,

FYI this compiled ok when I set board to a Wemos D1 mini (ESP8266)

When I moved to a Wemos Lolin32 (or any ESP32 board), I had to comment out the WireBegin line for it to compile... and then work.

I'm not advanced enough to know why, more an FYI

**Comment by G6EJD** [comment]
There is no wire.begin in this version, it’s a serial output version only, I think you were looking at the OLED display versions and probably didn’t have the library installed for the display that has the #include <wire.h> line so that wire.begin would compile ok.
